name: "bert"
platform: "pytorch_libtorch"
version_policy: {all{}}
input [
  {
    name: "input__0"
    data_type: TYPE_INT64
    dims: [ -1, 512 ]
  },
  {
    name: "input__1"
    data_type: TYPE_INT64
    dims: [ -1, 512 ]
  },
  {
    name: "input__2"
    data_type: TYPE_INT64
    dims: [ -1, 512 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ -1, 112 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]